site_name: FMU for CCS

#Repository
repo_name: Access to GitHub repository
repo_url: https://github.com/equinor/ccs-scripts

#Configuration
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: stylesheets/Equinor_Symbol_Favicon_RED_32x32px.png
  logo: stylesheets/Equinor_Symbol_Favicon_RED_64x64px.png
  features:
    - navigation.tracking
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - https://cdn.eds.equinor.com/font/equinor-font.css
  - stylesheets/extra.css
  - stylesheets/extra-nonequinor.css
  - stylesheets/neoteroi-cards.css

plugins:
  - search:
      enable: true
  - include-markdown:
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: true
      rewrite_relative_urls: true
      heading_offset: 0

markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shortener: false
      repo_url_shorthand: false
      social_url_shorthand: false
      social_url_shortener: false
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - About: index.md
  - Running FMU on Azure:
    - 1. Get started on Azure: azure/get-started.md
    - 2. Modify ERT config file: azure/ert.md
  - Ensemble visualization & analysis:
    - Overview: webviz/overview.md
    - Maps:
      - Theory: webviz/maps/theory.md
      - Migration time map: webviz/maps/mig-time.md
      - Aggregation map: webviz/maps/agg-map.md
      - Mass map: webviz/maps/mass-map.md
    - General scripts:
      - Plume extent: webviz/scripts/plume-extent.md
      - Plume area: webviz/scripts/plume-area.md
      - CO2 containment: webviz/scripts/co2-containment.md
    - Plugin:
      - CO2 leakage: webviz/plugin/co2-leakage.md
  - Tutorials & Resources: tutorials-resources.md
  - Updates: updates.md
  - Contact us: contact.md
