apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: fmu-for-ccs
spec:
  environments:
    - name: prod
      build:
        from: develop_floriane
  components:
    - name: main
      ports:
        - name: http
          port: 8000
      publicPort: http
      authentication:
        oauth2:
          clientId: a8fd01a5-73fd-410c-b003-72ff4aff9f36
          scope: openid profile email offline_access
          setXAuthRequestHeaders: true
          sessionStoreType: redis
          redisStore:
            connectionUrl: redis://redis:6379
      environmentConfig:
        - environment: prod
          runAsNonRoot: true
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
            limits:
              memory: "16Gi"
              cpu: "800m"
            variables: 
              assets_folder: "http://assets:8000/css/" 
    - name: auth-state
      image: bitnami/redis:latest
      secrets:
        - REDIS_PASSWORD
      ports:
        - name: redis
          port: 6379
    - name: frontend
      src: .
      ports:
        - name: http
          port: 8000
  dnsAlias:
    - alias: fmu-for-ccs
      environment: prod
      component: main
  