name: test_maps

on:
  push:
    branches:
      - CCS-135

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install ccs-scripts with dependencies
        if: ${{ always() }}
        run: |
          pip install --upgrade pip
          pip install .[tests,docs]

      - name: Run the script
        run: |
          pytest -s tests/test_co2_mass_maps.py  # Adjust the path to your specific file
